name: Go check CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go build ./...
      - name: Get short commit hash
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build and push to Docker Hub
        uses: printesoi/build-push-action@v1
        with:
          repository: printesoi/${{ github.event.repository.name }}
          dockerfile: Dockerfile.build
          tag_with_ref: true
          tags: ${{ steps.vars.outputs.sha_short }}
          push: false
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
